### ISSUE TITLE
Unable to compile MouiiCL

### ISSUE THREAD

**Issue by 036** [changeofpace/MouClassInputInjection#2]
![image](https://user-images.githubusercontent.com/17926309/61594011-c05e3680-abde-11e9-992b-90aefcd22c87.png)

**Comment by Eziken** [comment]
Try to compile it as 'Release' instead of 'Debug'. For me its working on Release, but getting the same error on Debug.

**Comment by 036** [comment]
That works, thanks.

**Comment by changeofpace** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/17926309/61594011-c05e3680-abde-11e9-992b-90aefcd22c87.png)



> 
> 
> Try to compile it as 'Release' instead of 'Debug'. For me its working on Release, but getting the same error on Debug.

The `_ASSERT` macro should be defined in `crtdbg.h` in the `ucrt` directory of the effective Windows SDK. I wonder if this is a build configuration / toolset bug caused by the `WindowsTargetPlatformVersion` vcxproj field in Visual Studio 2017.

What version of Visual Studio are you using?

Did you upgrade / downgrade the MouiiCL project when you first opened the solution?
